# Generated by Django 6.0.6 on 2026-07-04 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure_core', '0004_alter_category_parent_alter_language_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_living', models.BooleanField(default=True)),
                ('community_note', models.CharField(blank=True, help_text="For speakers from outside the five Akita communities — specify their community of origin here (e.g. 'Peremabiri', 'Ekeremor').", max_length=255)),
                ('community', models.ForeignKey(blank=True, help_text='One of the five Akita clan communities, if the speaker is an original community member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speakers', to='infrastructure_core.community')),
                ('documented_by', models.ForeignKey(help_text='The contributor: Interviewer/Narrator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documented_speakers', to=settings.AUTH_USER_MODEL)),
                ('speaker_user_account', models.OneToOneField(blank=True, help_text='For speakers who are also registered users', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('community__isnull', True), ('community_note', ''), _connector='OR'), name='speaker_community_mutex')],
            },
        ),
    ]
