# Generated by Django 6.0.6 on 2026-07-04 09:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentation_lexicon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alphabet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronunciation', models.FileField(blank=True, null=True, upload_to='records/%Y/%m', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg'])])),
                ('order', models.PositiveSmallIntegerField()),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['orthographic_system', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GraphemeRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notation', models.CharField(max_length=10, unique=True)),
                ('character_count', models.PositiveSmallIntegerField(default=1, help_text='Number of Unicode characters that compose this grapheme.1 for monographs, 2 for digraphs, 3 for trigraphs, etc.')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhonemeRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipa', models.CharField(help_text='The IPA character representing the sound', max_length=10, unique=True)),
                ('sound', models.FileField(blank=True, null=True, upload_to='records/%Y/%m', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg'])])),
                ('is_vowel', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GraphemeFeaturedExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grapheme_feature_appearances', to='documentation_lexicon.lexicalentry')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_entries', to='documentation_orthography.alphabet')),
            ],
            options={
                'ordering': ['priority'],
                'unique_together': {('letter', 'entry')},
            },
        ),
        migrations.AddField(
            model_name='alphabet',
            name='featured_examples',
            field=models.ManyToManyField(blank=True, related_name='featured_in_alphabet_entries', through='documentation_orthography.GraphemeFeaturedExample', to='documentation_lexicon.lexicalentry'),
        ),
        migrations.AddField(
            model_name='alphabet',
            name='grapheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alphabet_placements', to='documentation_orthography.graphemeregister'),
        ),
        migrations.CreateModel(
            name='OrthographicSystemRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name used to identify this particular collection of graphemes-phonemes pairs', max_length=100, unique=True)),
                ('is_default', models.BooleanField(default=False, help_text="The default/fixed system for the server side.Only one True must exist at a time. It is transliterated to client's choice per toggle request.")),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_system')],
            },
        ),
        migrations.AddField(
            model_name='alphabet',
            name='orthographic_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alphabet_entries', to='documentation_orthography.orthographicsystemregister'),
        ),
        migrations.AddField(
            model_name='alphabet',
            name='phoneme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alphabet_placements', to='documentation_orthography.phonemeregister'),
        ),
        migrations.AlterUniqueTogether(
            name='alphabet',
            unique_together={('orthographic_system', 'grapheme'), ('orthographic_system', 'order')},
        ),
    ]
