# Generated by Django 6.0.4 on 2026-05-20 17:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AkitaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('editor', 'Editor/Moderator'), ('contributor', 'Contributor')], db_index=True, default='contributor', max_length=20)),
                ('contributor_level', models.PositiveSmallIntegerField(default=1, help_text='Higher levels can deactivate lower levels (1-99)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('registration_notes', models.TextField(blank=True, help_text='Context of physical identification')),
                ('speaks_for_self', models.BooleanField(default=True, help_text='This contributor is also a speaker')),
                ('elevated_at', models.DateTimeField(blank=True, null=True)),
                ('elevation_notes', models.TextField(blank=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.community')),
                ('elevated_by', models.ForeignKey(blank=True, help_text='Admin who promoted this user to Editor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elevated_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('registered_by', models.ForeignKey(blank=True, help_text='Admin or Editor who physically identified this contributor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_users', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-contributor_level', 'date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SpeakerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('clan_name', models.CharField(blank=True, max_length=255)),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_living', models.BooleanField(default=True)),
                ('documented_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documented_speakers', to=settings.AUTH_USER_MODEL)),
                ('user_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaker_profile', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speakers', to='core.community')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
