# Generated by Django 6.0.6 on 2026-06-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_users', '0001_initial'),
        ('infrastructure_core', '0002_alter_akitacommunity_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='speakerprofile',
            constraint=models.CheckConstraint(condition=models.Q(('community__isnull', True), ('community_note', ''), _connector='OR'), name='speaker_community_mutex'),
        ),
    ]
