# Generated by Django 6.0.4 on 2026-06-04 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='akitauser',
            managers=[
            ],
        ),
    ]
