# Generated by Django 6.0.4 on 2026-06-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_users', '0002_alter_akitauser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akitauser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
