# Generated by Django 6.0.6 on 2026-06-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_users', '0002_speakerprofile_speaker_community_mutex'),
    ]

    operations = [
        migrations.AddField(
            model_name='akitauser',
            name='slug',
            field=models.SlugField(blank=True, help_text='A unique URL-friendly string identifier.', max_length=150, unique=True),
        ),
    ]
