# Generated by Django 6.0.6 on 2026-07-04 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity_users', '0003_akitauser_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='speakerprofile',
            name='speaker_community_mutex',
        ),
        migrations.DeleteModel(
            name='SpeakerProfile',
        ),
    ]
