# Generated by Django 6.0.6 on 2026-06-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='akitacommunity',
            options={'ordering': ['name'], 'verbose_name_plural': 'akita communities'},
        ),
    ]
