# Generated by Django 6.0.6 on 2026-06-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_core', '0002_alter_akitacommunity_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialect',
            name='name',
            field=models.CharField(default='Akita', max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
