# Generated by Django 6.0.6 on 2026-07-04 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_core', '0003_alter_dialect_name_alter_language_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='infrastructure_core.category'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(default='Ijaw', max_length=100, unique=True),
        ),
    ]
