# Generated by Django 6.0.7 on 2026-07-09 21:47

import apps.common.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure_core', '0004_alter_category_parent_alter_language_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammaticalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Grammatical Categories',
            },
        ),
        migrations.CreateModel(
            name='Illustration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/%Y/%m/%d/')),
                ('media_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('image', 'Image')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pronunciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipa', models.CharField(blank=True, help_text='IPA transcription of the word', max_length=200, null=True)),
                ('transcription_type', models.CharField(choices=[('phonemic', 'Phonemic (Broad)'), ('phonetic', 'Phonetic (Narrow)'), ('both', 'Both (combined notation)')], default='phonemic', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_form', models.CharField(max_length=50, unique=True)),
                ('meaning', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SemanticDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SemanticRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SemanticRelationTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(unique=True)),
                ('translation', models.TextField(blank=True, help_text='a direct substitute')),
                ('definition', models.TextField(blank=True, help_text='an elaborate explanation of meaning', null=True)),
                ('is_ideophone', models.BooleanField(default=False)),
                ('cultural_note', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['entry', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Anonymous identifier, e.g., SPK01', max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsageLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.common.storage.set_user_uploaded_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('translation', models.TextField(blank=True)),
                ('interlinear_gloss', models.TextField(blank=True)),
                ('dialect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure_core.dialect')),
            ],
        ),
        migrations.CreateModel(
            name='LexicalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(db_index=True, help_text='The headword as it appears in the dictionary.', max_length=200)),
                ('is_compound', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(blank=True, editable=False, help_text='Alphabetical rank in the dictionary. Computed automatically by the collation service. NULL until the grapheme sequence is complete.', null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('constituents', models.ManyToManyField(blank=True, help_text='Component words that make up this compound entry.', related_name='compounds', to='documentation_lexicon.lexicalentry')),
                ('dialect', models.ForeignKey(limit_choices_to={'is_target': True}, on_delete=django.db.models.deletion.CASCADE, related_name='lexical_entries', to='infrastructure_core.dialect')),
                ('language', models.ForeignKey(limit_choices_to={'is_target': True}, on_delete=django.db.models.deletion.CASCADE, related_name='lexical_entries', to='infrastructure_core.language')),
                ('variant_form', models.ManyToManyField(blank=True, help_text='other spellings for this same word in same orthographic system', to='documentation_lexicon.lexicalentry')),
            ],
            options={
                'verbose_name_plural': 'Lexical Entries',
            },
        ),
        migrations.CreateModel(
            name='Inflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='e.g., past tense, plural, gerund', max_length=100, null=True)),
                ('form', models.CharField(blank=True, help_text='The inflected form of the word', max_length=200, null=True)),
                ('note', models.TextField(blank=True)),
                ('dialect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure_core.dialect')),
                ('entry', models.ForeignKey(blank=True, help_text='If inflection is entry-based, specify, else null for sense-based inflection', null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentation_lexicon.lexicalentry')),
            ],
        ),
        migrations.CreateModel(
            name='GrammaticalFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentation_lexicon.grammaticalcategory')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grammatical_features', to='documentation_lexicon.lexicalentry')),
            ],
        ),
        migrations.CreateModel(
            name='Etymology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_text', models.TextField(blank=True)),
                ('proto_form', models.CharField(blank=True, max_length=200)),
                ('entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etymology', to='documentation_lexicon.lexicalentry')),
                ('source_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etymology_sources', to='documentation_lexicon.lexicalentry')),
            ],
        ),
        migrations.CreateModel(
            name='Collocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.TextField(blank=True)),
                ('expression', models.TextField(blank=True)),
                ('basic_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collocations', to='documentation_lexicon.lexicalentry')),
                ('other_entries', models.ManyToManyField(related_name='collocation_with', to='documentation_lexicon.lexicalentry')),
            ],
        ),
        migrations.CreateModel(
            name='LexicalEntryGrapheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(help_text='Zero-indexed position of this grapheme within the headword.')),
                ('is_final', models.BooleanField(default=False, help_text='True on the last grapheme slot only. Triggers concatenation validation and, on success, collation positioning.')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grapheme_slots', to='documentation_lexicon.lexicalentry')),
            ],
            options={
                'ordering': ['entry', 'slot'],
            },
        ),
    ]
