# Generated by Django 6.0.7 on 2026-07-09 21:47

import django.db.models.constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentation_lexicon', '0001_initial'),
        ('documentation_orthography', '0001_initial'),
        ('infrastructure_core', '0004_alter_category_parent_alter_language_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lexicalentrygrapheme',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_slots', to='documentation_orthography.alphabet'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='illustration',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentation_lexicon.mediafile'),
        ),
        migrations.AddField(
            model_name='example',
            name='audio',
            field=models.ManyToManyField(blank=True, limit_choices_to={'media_type': 'audio'}, to='documentation_lexicon.mediafile'),
        ),
        migrations.AddField(
            model_name='collocation',
            name='audio',
            field=models.ManyToManyField(blank=True, limit_choices_to={'media_type': 'audio'}, to='documentation_lexicon.mediafile'),
        ),
        migrations.AddField(
            model_name='pronunciation',
            name='audio',
            field=models.ManyToManyField(blank=True, limit_choices_to={'media_type': 'audio'}, related_name='pronunciation_audio', to='documentation_lexicon.mediafile'),
        ),
        migrations.AddField(
            model_name='pronunciation',
            name='dialect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure_core.dialect'),
        ),
        migrations.AddField(
            model_name='pronunciation',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciations', to='documentation_lexicon.lexicalentry'),
        ),
        migrations.AddField(
            model_name='lexicalentry',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_entries', to='documentation_lexicon.root'),
        ),
        migrations.AddField(
            model_name='semanticdomain',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdomains', to='documentation_lexicon.semanticdomain'),
        ),
        migrations.AddField(
            model_name='semanticrelation',
            name='source_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_targets', to='documentation_lexicon.lexicalentry'),
        ),
        migrations.AddField(
            model_name='semanticrelation',
            name='target_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_sources', to='documentation_lexicon.lexicalentry'),
        ),
        migrations.AddField(
            model_name='semanticrelation',
            name='relation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_pair', to='documentation_lexicon.semanticrelationtypes'),
        ),
        migrations.AddField(
            model_name='sense',
            name='domains',
            field=models.ManyToManyField(blank=True, to='documentation_lexicon.semanticdomain'),
        ),
        migrations.AddField(
            model_name='sense',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senses', to='documentation_lexicon.lexicalentry'),
        ),
        migrations.AddField(
            model_name='sense',
            name='gloss_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glosses', to='infrastructure_core.language'),
        ),
        migrations.AddField(
            model_name='sense',
            name='register',
            field=models.ManyToManyField(blank=True, help_text='Register or style of usage - pragmatics', to='documentation_lexicon.register'),
        ),
        migrations.AddField(
            model_name='inflection',
            name='sense',
            field=models.ForeignKey(blank=True, help_text='The inflection is associated with this sense of the entry', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inflections', to='documentation_lexicon.sense'),
        ),
        migrations.AddField(
            model_name='illustration',
            name='sense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='illustrations', to='documentation_lexicon.sense'),
        ),
        migrations.AddField(
            model_name='example',
            name='sense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='documentation_lexicon.sense'),
        ),
        migrations.AddField(
            model_name='communitynote',
            name='sense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_notes', to='documentation_lexicon.sense'),
        ),
        migrations.AddField(
            model_name='source',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='documentation_lexicon.lexicalentry'),
        ),
        migrations.AddField(
            model_name='source',
            name='example',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='documentation_lexicon.example'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='dialect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure_core.dialect'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='Contributor who made the recording', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_speakers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='source',
            name='speaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentation_lexicon.speaker'),
        ),
        migrations.AddField(
            model_name='pronunciation',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentation_lexicon.speaker'),
        ),
        migrations.AddField(
            model_name='example',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentation_lexicon.speaker'),
        ),
        migrations.AddField(
            model_name='collocation',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentation_lexicon.speaker'),
        ),
        migrations.AddField(
            model_name='sense',
            name='usage_label',
            field=models.ForeignKey(blank=True, help_text='Register or style of usage - pragmatics', null=True, on_delete=django.db.models.deletion.CASCADE, to='documentation_lexicon.usagelabel'),
        ),
        migrations.AlterUniqueTogether(
            name='lexicalentrygrapheme',
            unique_together={('entry', 'slot')},
        ),
        migrations.AddConstraint(
            model_name='lexicalentry',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('position',), name='lexical_entry_position_unique'),
        ),
        migrations.AlterUniqueTogether(
            name='lexicalentry',
            unique_together={('lemma', 'language', 'dialect')},
        ),
        migrations.AlterUniqueTogether(
            name='semanticrelation',
            unique_together={('source_entry', 'target_entry', 'relation_type')},
        ),
        migrations.AlterUniqueTogether(
            name='sense',
            unique_together={('entry', 'order')},
        ),
    ]
